<?php
$data = array (
  3 => 
  array (
    'cat_id' => '3',
    'cat_desc' => '',
    'cat_name' => '产品类型一',
    'measure_unit' => '0',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => '4',
    'level' => 0,
    'id' => '3',
    'name' => '产品类型一',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_desc' => '',
    'cat_name' => '产品类型一1',
    'measure_unit' => '2',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '产品类型一1',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_desc' => '',
    'cat_name' => '产品类型二',
    'measure_unit' => '0',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 0,
    'id' => '4',
    'name' => '产品类型二',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_desc' => '',
    'cat_name' => '产品类型三',
    'measure_unit' => '0',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '5',
    'name' => '产品类型三',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_desc' => '',
    'cat_name' => '产品类型四',
    'measure_unit' => '0',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '产品类型四',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_desc' => '',
    'cat_name' => '产品类型五',
    'measure_unit' => '0',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '产品类型五',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_desc' => '',
    'cat_name' => '产品类型六',
    'measure_unit' => '0',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '产品类型六',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_desc' => '',
    'cat_name' => '产品类型七',
    'measure_unit' => '0',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '9',
    'name' => '产品类型七',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_desc' => '',
    'cat_name' => '产品类型八',
    'measure_unit' => '0',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '10',
    'name' => '产品类型八',
  ),
);
?>